aplicacao/urls.py
from django.urls import path
from . import views

app_name = 'aplicacao'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('compra_efetuada/', views.CompraEfetuadaView.as_view(), name='compra_efetuada'),
    path('compra_erro/', views.CompraErroView.as_view(), name='compra_erro'),
]

primeira_api_pagamento/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicacao.urls'))
]

aplicacao/models.py
from django.db import models

# Create your models here.

aplicacao/views.py
from django.shortcuts import render
from django.views import View

class HomeView(View):

    def get(self, request):
        return render(request, 'home.html')
    
class CompraEfetuadaView(View):

    def get(self, request):
        return render(request, 'compra_efetuada.html')
    
class CompraErroView(View):

    def get(self, request):
        return render(request, 'compra_erro.html')

aplicacao/templates/compra_efetuada.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compra efetuada</title>
</head>
<body>
    <h1>Efetuada!</h1>
    <a href="{% url 'aplicacao:home' %}">
        <p>Voltar</p>
    </a>
</body>
</html>

aplicacao/templates/compra_erro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compra efetuada</title>
</head>
<body>
    <h1>Erro!</h1>
    <a href="{% url 'aplicacao:home' %}">
        <p>Voltar</p>
    </a>
</body>
</html>

aplicacao/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'aplicacao/css/home.css' %}">
</head>
<body>
    <h1>Loja virtual</h1>

    <h3>blusinha - R$0.01</h3>
    <button>comprar</button>
</body>
</html>